layout_spectrum: 0.09335794532671571
typography_spectrum: 0.29443536256439984
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.6633858794812113
  lightness: 0.7476594946347177
  saturation: 0.3146373420022428
  rhythmicContrast: 0.09692946425639093
name: plerichiu
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
