name: plerichiu
favicon: null
layout_spectrum: 0.51336
typography_spectrum: 0.15381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#100e0f'
    - '#d5c3bd'
    - '#bf8c6f'
    - '#995d4a'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
